GM-1400 - Rework md2conf Tool
Dagrofa-Merkur/md_to_conf pull request #3
Opened 2020-05-11 16:13 UTC by nora-ambroz

2020-05-12 12:54 UTC, fpeter8 requested changes
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @fpeter8, @gaborvolczer, @nbali, and @nora-ambroz)

___
*[md2conf.py, line 38 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vwle8VAE-041oKr2:-M77vwle8VAE-041oKr3:b-i42uy6) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/25aac653f66f3d6bf0ea89bf4af93e98a2259fc1/md2conf.py#L38)):*
> ```Python
>                     help="Confluence Space key for the page. If omitted, will use user space.")
> PARSER.add_argument('-u', '--username', help='Confluence username if $CONFLUENCE_USERNAME not set.')
> PARSER.add_argument('-p', '--apikey', help='Confluence API key if $CONFLUENCE_API_KEY not set.')
> ```

you've
- removed the command line parameter
- removed the system variable
- added a file parameter

you did nothing of the above for the username/orgname. Adding a special case for the API key is fine, but if you removed the system variable, why not from the other parameters? why do I have to specify the user name, and not save that to the file?

what I'm saying is that this is inconsistent, this is not a de-facto 'go with this solution'

if you're not sure what is the advantage/disadvantage of each method, ask
___
*[md2conf.py, line 44 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77w_cg22GgoQGduICQ:-M77w_cg22GgoQGduICR:bmaw653) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/25aac653f66f3d6bf0ea89bf4af93e98a2259fc1/md2conf.py#L44)):*
> ```Python
>                          'If orgname contains a dot, considered as the fully qualified domain name.'
>                          'e.g. https://XXX')
> PARSER.add_argument('-a', '--ancestor',
> ```

are we not parameterizing this?
___
*[md2conf.py, line 62 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vFP9BtB0lBhUK6yb:-M77vFPACzxE6vAo8rkI:b-o1x7ay) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L62)):*
> ```Python
>     LOGGER.setLevel(getattr(logging, ARGS.loglevel.upper(), None))
> 
>     DOCUMENTATION_ROOT = '..\\dagrofa-merkur\\docs'
> ```

make this parametrizable; not everyone will check this out to the same path
___
*[md2conf.py, line 63 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vMAD79A_WPboR77J:-M77vMAD79A_WPboR77K:b-ve4t7l) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L63)):*
> ```Python
> 
>     DOCUMENTATION_ROOT = '..\\dagrofa-merkur\\docs'
>     DOCUMENTATION_TEMPLATE = 'template.md'
> ```

I'm not sure yet what this does
___
*[md2conf.py, line 64 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vA7qAU60OftaOd6r:-M77vA7r1YCt_uNy9Uon:b-ha80cn) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L64)):*
> ```Python
>     DOCUMENTATION_ROOT = '..\\dagrofa-merkur\\docs'
>     DOCUMENTATION_TEMPLATE = 'template.md'
>     LOG_FILE = 'logs\\logs.txt'
> ```

if you append the current timestamp you can easily see the logs from different runs
___
*[README.md, line 174 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77usra4tyhFWPo6elj:-M77usrb3KYHodCs_UdB:bnay2mz) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/25aac653f66f3d6bf0ea89bf4af93e98a2259fc1/README.md#L174)):*
> ```Markdown
> ```
> 
> ## Miscellaneous
> ```

:cry: 


<!-- Sent from Reviewable.io -->

2020-05-27 10:28 UTC, gaborvolczer reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @gaborvolczer, @nbali, and @nora-ambroz)



<!-- Sent from Reviewable.io -->

2020-06-15 11:55 UTC, fpeter8 requested changes
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 12 unresolved discussions (waiting on @nbali and @nora-ambroz)

___
*[md2conf.py, line 62 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vFP9BtB0lBhUK6yb:-M9rmxxZ4O_TwX-er2xb:bu3ugxq) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L62)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

make this parametrizable; not everyone will check this out to the same path
</blockquote></details>

also this path only works on windows; use `/` instead of `\` to make it platform-independent (python will translate it to windows path)
___
*[md2conf.py, line 64 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vA7qAU60OftaOd6r:-M9rn9QKErQ8jEqd1kTg:b-rr4zys) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L64)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

if you append the current timestamp you can easily see the logs from different runs
</blockquote></details>

(append to the filename)
also when you first check the repo out the `logs` folder is missing and you get an exception
___
*[md2conf.py, line 656 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rnp8JAS6G7M3_eNTL:-M9rnp8JAS6G7M3_eNTM:bjv4lid) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L656)):*
> ```Python
>     html = process_refs(html)
>     html = resolve_refs(html, filepath)
>     LOGGER.debug('html: %s', html)
> ```

it might be nice to add a new parameter, and if it is set, create a separate `.html` file in the logs folder. That way I don't have to scroll all the way in the log file. (this is optional)
log which HTML we're logging; right now I cannot search for a specific page in the logs
___
*[md2conf.py, line 715 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9roFb672HBg_GNnpEZ:-M9roFb672HBg_GNnpE_:bnvp9hg) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L715)):*
> ```Python
>     """
>     log_file = open(LOG_FILE, 'a')
>     log_file.write(html)
> ```

write a line above that logs the original markdown name (for searchability)
___
*[md2conf.py, line 740 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9roRrwCRfu7lBoSO5k:-M9roRrwCRfu7lBoSO5l:be5es8w) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L740)):*
> ```Python
>     """
>     root = os.path.abspath(DOCUMENTATION_ROOT)
>     md_file = directory.split('\\')[-1] + '.md'
> ```

separator
___
*[md2conf.py, line 741 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9roTiL62aRY2qcov2X:-M9roTiL62aRY2qcov2Y:be5es8w) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L741)):*
> ```Python
>     root = os.path.abspath(DOCUMENTATION_ROOT)
>     md_file = directory.split('\\')[-1] + '.md'
>     return root + '\\' + md_file
> ```

separator
___
*[md2conf.py, line 841 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rp3Bg3oSzUSU4VHa2:-M9rp3Bg3oSzUSU4VHa3:b6bbqd5) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L841)):*
> ```Python
>             sys.exit(1)
> 
>         create_dir_landing_page(doc_file, DOCUMENTATION_ROOT, [])
> ```

the `ancestor` parameter is empty here, but we should create it under the root element, not beside it
___
*[md2conf.py, line 781 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rpE0l1BLvDwFRUuZZ:-M9rpE0m4o3MTMEfRW3K:b-4yr6dt) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L781)):*
> ```Python
> def handle_not_cleared_page(page, title):
>     LOGGER.warning('Page not cleared before recreating pages, because it is not a child page of Documentation: %s', title)
>     input_value = input('Type \'yes\' if you wish to delete the page.')
> ```

newline


<!-- Sent from Reviewable.io -->

2020-06-15 11:56 UTC, fpeter8 requested changes
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 13 unresolved discussions (waiting on @nbali and @nora-ambroz)

*[a discussion](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rpIqx8UWeSap_eu-s:-M9rpIqx8UWeSap_eu-t:bu2yrc1) (no related file):*
right now the tool works by deleting all pages under the documentation root, then re-creating everything. Please estimate how much it would cost to update/patch the pages instead of deleting them. Do not start on it until you get the OK.

---


<!-- Sent from Reviewable.io -->

2020-06-19 17:15 UTC, nbali requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 18 unresolved discussions (waiting on @nora-ambroz)

___
*[md2conf.py, line 322 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACNuHM1LRlE2d9asnN:-MACNuHM1LRlE2d9asnO:b-471w5g) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L322)):*
> ```Python
>     page_ids = get_child_pages_recursively(page_id)
> 
>     for page_id in page_ids:
> ```

if you have to do this then that method isn't recursive :)
___
*[md2conf.py, line 332 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACNNq-2zKRlhzd3O_B:-MACNNq-2zKRlhzd3O_C:bvrpgb3) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L332)):*
> ```Python
> def get_child_pages_recursively(page_id):
>     """
>      Retrieve immediate child page ids
> ```

"recursively" vs "immediate"?
___
*[md2conf.py, line 789 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACS_gR1tn7RvwZJ9ta:-MACS_gR1tn7RvwZJ9tb:bl4p8oo) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L789)):*
> ```Python
> 
> 
> def create_dir_landing_page_recursively(dir_landing_page_file, directory):
> ```

is there any case when the dir_landing_page_file isn't calculatable from directory? doesn't it have a 1-to-1 mapping?

```
 create_dir_landing_page_recursively(get_landing_page_doc_file(directory), directory)
 create_dir_landing_page_recursively(get_landing_page_doc_file(ancestor_landing_page_dir), ancestor_landing_page_dir)
```
essentially this is what you call only
___
*[md2conf.py, line 803 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACXaZL45N2AaH7-mZ7:-MACXaZL45N2AaH7-mZ8:b-lqy7io) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L803)):*
> ```Python
> 
>     if ancestor_page:
>         page_as_ancestor = create_dir_landing_page(dir_landing_page_file, directory, get_page_as_ancestor(ancestor_page.id))
> ```

this creates the current one even if it already exists, so if called through recursion it might be created multiple times
___
*[md2conf.py, line 805 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACQ9_u5cfMqqoVoma9:-MACQ9_u5cfMqqoVomaA:b-5daxg2) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L805)):*
> ```Python
>         page_as_ancestor = create_dir_landing_page(dir_landing_page_file, directory, get_page_as_ancestor(ancestor_page.id))
>     else:
>         page_as_ancestor = create_dir_landing_page_recursively(ancestor_landing_page_file, ancestor_landing_page_dir)
> ```

in this case you don't create the current one - I mean this creates every ancestor page, except the current one - I don't think that is what you wanted to do 


<!-- Sent from Reviewable.io -->

2020-06-19 17:24 UTC, nbali requested changes
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 18 unresolved discussions (waiting on @fpeter8 and @nora-ambroz)

*[a discussion](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rpIqx8UWeSap_eu-s:-MACaqwAC4pNQ6NTAIPX:b3kqx) (no related file):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

right now the tool works by deleting all pages under the documentation root, then re-creating everything. Please estimate how much it would cost to update/patch the pages instead of deleting them. Do not start on it until you get the OK.
</blockquote></details>

.

---


<!-- Sent from Reviewable.io -->

2020-06-26 12:37 UTC, nora-ambroz reviewed
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: 0 of 3 files reviewed, 17 unresolved discussions (waiting on @fpeter8 and @nbali)

*[a discussion](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rpIqx8UWeSap_eu-s:-MAg6sID4s4Hz2GFYuRp:b-896fix) (no related file):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

---
___
*[md2conf.py, line 38 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vwle8VAE-041oKr2:-MA_fruyDR3RXMDpxHIM:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/25aac653f66f3d6bf0ea89bf4af93e98a2259fc1/md2conf.py#L38)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

you've
- removed the command line parameter
- removed the system variable
- added a file parameter

you did nothing of the above for the username/orgname. Adding a special case for the API key is fine, but if you removed the system variable, why not from the other parameters? why do I have to specify the user name, and not save that to the file?

what I'm saying is that this is inconsistent, this is not a de-facto 'go with this solution'

if you're not sure what is the advantage/disadvantage of each method, ask
</blockquote></details>

Done.
___
*[md2conf.py, line 44 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77w_cg22GgoQGduICQ:-MA_wn4e3y6J9LwxycdC:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/25aac653f66f3d6bf0ea89bf4af93e98a2259fc1/md2conf.py#L44)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

are we not parameterizing this?
</blockquote></details>

Done.
___
*[md2conf.py, line 62 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vFP9BtB0lBhUK6yb:-MAa8m2E183JqE7wtnvu:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L62)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

also this path only works on windows; use `/` instead of `\` to make it platform-independent (python will translate it to windows path)
</blockquote></details>

Done.
___
*[md2conf.py, line 63 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vMAD79A_WPboR77J:-MA_yoc9CZZISRDy810K:b-4voskv) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L63)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

I'm not sure yet what this does
</blockquote></details>

There are template.md files in pipeline, tool and masterdata folder. I thought, these are not relevant to the Confluence readers, so they are not synced at the moment. Let me know if you don't want them skipped. 
___
*[md2conf.py, line 64 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vA7qAU60OftaOd6r:-MAa8jX96S3LsXGeGNJH:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L64)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

(append to the filename)
also when you first check the repo out the `logs` folder is missing and you get an exception
</blockquote></details>

Done.
___
*[md2conf.py, line 656 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rnp8JAS6G7M3_eNTL:-MAaiU613fsH6KLBKxda:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L656)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

it might be nice to add a new parameter, and if it is set, create a separate `.html` file in the logs folder. That way I don't have to scroll all the way in the log file. (this is optional)
log which HTML we're logging; right now I cannot search for a specific page in the logs
</blockquote></details>

Done.
___
*[md2conf.py, line 715 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9roFb672HBg_GNnpEZ:-MAamce72VbV44j7QdCR:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L715)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

write a line above that logs the original markdown name (for searchability)
</blockquote></details>

Done.
___
*[md2conf.py, line 740 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9roRrwCRfu7lBoSO5k:-MAfSpso26h-ekJYyI9L:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L740)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

separator
</blockquote></details>

Done.
___
*[md2conf.py, line 741 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9roTiL62aRY2qcov2X:-MAfSpXICCXACEpbxUKj:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L741)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

separator
</blockquote></details>

Done.
___
*[md2conf.py, line 841 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rp3Bg3oSzUSU4VHa2:-MAawk1r-niefyKAZDgA:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L841)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

the `ancestor` parameter is empty here, but we should create it under the root element, not beside it
</blockquote></details>

Done.
___
*[md2conf.py, line 322 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACNuHM1LRlE2d9asnN:-MAa-xu8Cn0gSX_3S9Uu:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L322)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

if you have to do this then that method isn't recursive :)
</blockquote></details>

Done.
___
*[md2conf.py, line 332 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACNNq-2zKRlhzd3O_B:-MAa-zdq4407QW4DOQCZ:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L332)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

"recursively" vs "immediate"?
</blockquote></details>

Done.
___
*[md2conf.py, line 781 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M9rpE0l1BLvDwFRUuZZ:-MAawcNQEDts5fl4_0JB:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L781)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.
___
*[md2conf.py, line 789 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACS_gR1tn7RvwZJ9ta:-MAe_Hmg4R1gUpYZERM1:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L789)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

is there any case when the dir_landing_page_file isn't calculatable from directory? doesn't it have a 1-to-1 mapping?

```
 create_dir_landing_page_recursively(get_landing_page_doc_file(directory), directory)
 create_dir_landing_page_recursively(get_landing_page_doc_file(ancestor_landing_page_dir), ancestor_landing_page_dir)
```
essentially this is what you call only
</blockquote></details>

Done.
___
*[md2conf.py, line 803 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACXaZL45N2AaH7-mZ7:-MAemf8UCThVY3GPQiTb:b-896fix) ([raw file]( [...]

2020-06-29 23:02 UTC, nbali requested changes
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 17 unresolved discussions (waiting on @fpeter8 and @nora-ambroz)

___
*[md2conf.py, line 322 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACNuHM1LRlE2d9asnN:-MB1EQwc64GFhjY1uR5h:b82i7c0) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L322)):*
<details><summary><i>Previously, nora-ambroz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if you have to do this then that method doesn't return "all" :)

for example `get_direct_child_pages` seems more accurate

at least in my opinion all and/or recursive means the whole tree, and direct and/or immediate only the next level
___
*[md2conf.py, line 332 at r2](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MACNNq-2zKRlhzd3O_B:-MB1EgwT320I4CM0M1qH:bjo7xtr) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/0aa5aba789ff766516a58953f1e3caad2e62362d/md2conf.py#L332)):*
<details><summary><i>Previously, nora-ambroz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

what does the api return? every page even a few levels down, or only the direct children?
___
*[md2conf.py, line 823 at r3](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MB1FqTjBtCPhrUu8AgH:-MB1FqTk30ImoxJJ6TK8:bcm3q74) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/b4666a56ce7a45823a50d4884141c602e3accf66/md2conf.py#L823)):*
> ```Python
> 
> 
> def get_or_create_page(ancestor_page, dir_landing_page_file, directory):
> ```

still an unnecessary extra parameter as dir_landing_page_file and directory has 1-to-1 mapping
___
*[md2conf.py, line 899 at r4](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MB1IXSJ859AJsrEBRHf:-MB1IXSJ859AJsrEBRHg:b-g62qla) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/53e4d86238db47e67b8122f891287308b5a976e6/md2conf.py#L899)):*
> ```Python
>     for original_child_page in original_child_pages:
>         if original_child_page not in active_pages:
>             delete_page(original_child_page)
> ```

this will delete everything if SIMULATE is true
___
*[README.md, line 92 at r6](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MB1JB1CEEor3dgn3IYj:-MB1JB1CEEor3dgn3IYk:bb7phvt) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/a5a588fca6aa741f72a36c697b241e3732c10f9e/README.md#L92)):*
> ```Markdown
> Use **-d** or **--delete** to delete pages that are under the parent folder specified by the **--ancestor** parameter.
> 
> Use **-c** or **--contentss** to generate a contents page.
> ```

typo


<!-- Sent from Reviewable.io -->

2020-06-30 08:16 UTC, nora-ambroz reviewed
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 17 unresolved discussions (waiting on @fpeter8 and @nbali)

___
*[md2conf.py, line 823 at r3](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MB1FqTjBtCPhrUu8AgH:-MB3HRuQ-aG-_QLkIMmU:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/b4666a56ce7a45823a50d4884141c602e3accf66/md2conf.py#L823)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

still an unnecessary extra parameter as dir_landing_page_file and directory has 1-to-1 mapping
</blockquote></details>

Done.
___
*[md2conf.py, line 899 at r4](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MB1IXSJ859AJsrEBRHf:-MB3HtGt76HKjKtlIlEf:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/53e4d86238db47e67b8122f891287308b5a976e6/md2conf.py#L899)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

this will delete everything if SIMULATE is true
</blockquote></details>

Done.
___
*[README.md, line 92 at r6](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MB1JB1CEEor3dgn3IYj:-MB3Hymb8gn9-7yiPOqR:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/a5a588fca6aa741f72a36c697b241e3732c10f9e/README.md#L92)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-01 15:46 UTC, fpeter8 requested changes
> Reviewed 3 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 6 unresolved discussions (waiting on @nbali and @nora-ambroz)

___
*[md2conf.py, line 63 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vMAD79A_WPboR77J:-MBA0w015M9uJQM5ghdn:bowdu3o) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L63)):*
<details><summary><i>Previously, nora-ambroz wrote…</i></summary><blockquote>

There are template.md files in pipeline, tool and masterdata folder. I thought, these are not relevant to the Confluence readers, so they are not synced at the moment. Let me know if you don't want them skipped. 
</blockquote></details>

this is a generic tool; we should not have any project specific exclusion filters inside. You can add this filter to the command line, but I'm fine with uploading 'useless' files with the rest.


<!-- Sent from Reviewable.io -->

2020-07-02 07:27 UTC, nora-ambroz reviewed
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @fpeter8 and @nbali)

___
*[md2conf.py, line 63 at r1](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-M77vMAD79A_WPboR77J:-MBDQ-kv98YaQTgdqrHc:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/06b16ca18697b39cb7fbe85a0262898206eaef37/md2conf.py#L63)):*
<details><summary><i>Previously, fpeter8 (Peter Farkas) wrote…</i></summary><blockquote>

this is a generic tool; we should not have any project specific exclusion filters inside. You can add this filter to the command line, but I'm fine with uploading 'useless' files with the rest.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-07-03 13:10 UTC, nbali requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 4 unresolved discussions (waiting on @fpeter8 and @nora-ambroz)

___
*[md2conf.py, line 333 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJmVlFE_lyMG3bVTN3:-MBJmVlFE_lyMG3bVTN4:bmstu0g) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L333)):*
> ```Python
> 
>     :param page_id: page id
>     :return: the ids of the direct child pages
> ```

this returns all now, not only direct :)
___
*[md2conf.py, line 818 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJmzCc4Tx2LIg_AQWC:-MBJmzCc4Tx2LIg_AQWD:bbcrprp) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L818)):*
> ```Python
>     ancestor_landing_page_title = get_title(ancestor_landing_page_file)
>     ancestor_page = get_page(ancestor_landing_page_title)
>     dir_landing_page_file = get_landing_page_doc_file(directory)
> ```

this should be completely unnecessary in this method, see my next omment
___
*[md2conf.py, line 829 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJmHxYDau8j_tJkiwD:-MBJmHxYDau8j_tJkiwE:b-haxoj0) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L829)):*
> ```Python
> 
> 
> def get_or_create_page(ancestor_page, directory):
> ```

you kept the directory here, but you removed the directory from the calls, I think you wanted to keep directory there as well


<!-- Sent from Reviewable.io -->

2020-07-03 13:24 UTC, nbali requested changes
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 6 unresolved discussions (waiting on @fpeter8 and @nora-ambroz)

___
*[md2conf.py, line 876 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJocF6AD5i5cZ1bB80:-MBJocF6AD5i5cZ1bB81:b-beres8) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L876)):*
> ```Python
>         if doc_landing_page:
>             original_child_pages.append(doc_landing_page_title)
>             original_child_pages = get_child_pages(doc_landing_page.id)
> ```

shouldn't this be an append? if not, then why do we add an entry in the previous line?
___
*[md2conf.py, line 916 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJpAFI4kHJ0ylTGDK0:-MBJpAFI4kHJ0ylTGDK1:brmggkc) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L916)):*
> ```Python
>         for original_child_page in original_child_pages:
>             if original_child_page not in active_pages:
>                 delete_page(original_child_page)
> ```

in my opinion, the most important aspect of a dry run/simulate run is the ability to see what it will destroy, the lack of creation can be always fixed later on, deletion not necessarily


<!-- Sent from Reviewable.io -->

2020-07-03 14:03 UTC, fpeter8 approved these changes
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 5 unresolved discussions (waiting on @nora-ambroz)



<!-- Sent from Reviewable.io -->

2020-07-03 14:03 UTC, fpeter8 approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 5 unresolved discussions (waiting on @nora-ambroz)



<!-- Sent from Reviewable.io -->

2020-07-30 09:26 UTC, nora-ambroz reviewed
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @fpeter8 and @nbali)

___
*[md2conf.py, line 333 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJmVlFE_lyMG3bVTN3:-MDQ9n0oAX1gV63lJwqK:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L333)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

this returns all now, not only direct :)
</blockquote></details>

Done.
___
*[md2conf.py, line 818 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJmzCc4Tx2LIg_AQWC:-MDQCo0_4ceFP8um2f_D:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L818)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

this should be completely unnecessary in this method, see my next omment
</blockquote></details>

Done.
___
*[md2conf.py, line 829 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJmHxYDau8j_tJkiwD:-MDQE0YMDLFVjac04kdI:b-pyzydj) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L829)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

you kept the directory here, but you removed the directory from the calls, I think you wanted to keep directory there as well
</blockquote></details>

Done. (?)


<!-- Sent from Reviewable.io -->

2020-07-30 11:55 UTC, nora-ambroz reviewed
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @fpeter8 and @nbali)

___
*[md2conf.py, line 876 at r8](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MBJocF6AD5i5cZ1bB80:-MDUMNRY-b1cE1FhB9qQ:b-nwzdgw) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/8fddc94dfedf1a6ce1713145b87f2b6defa1074b/md2conf.py#L876)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

shouldn't this be an append? if not, then why do we add an entry in the previous line?
</blockquote></details>

This should not be append. In python if you append [a,b] to [c], you will get [c, [a, b]] instead of [c, a, b]. Extend() is for iterables. The previous line is at the wrong place though.


<!-- Sent from Reviewable.io -->

2020-09-30 15:52 UTC, nbali requested changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 1 unresolved discussion (waiting on @nora-ambroz)

___
*[md2conf.py, line 339 at r10](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MIUgq8lBkdTW0khJhJR:-MIUgq8lBkdTW0khJhJS:b-gmjxt2) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/42c0217fc81641f3616390d319f7e5c6d17d5bbf/md2conf.py#L339)):*
> ```Python
> 
>     for page_id in page_ids:
>         child_pages = get_direct_child_pages(page_id)
> ```

just make this call `get_child_pages`, and you are done, you don't need the 
```
            for child_page_id in child_pages:
                get_child_pages(child_page_id)

```
part

not to mention you don't save that return value anywhere, so that call is useless


<!-- Sent from Reviewable.io -->

2020-10-01 11:29 UTC, nora-ambroz reviewed
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: all files reviewed, 1 unresolved discussion (waiting on @nbali)

___
*[md2conf.py, line 339 at r10](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3#-MIUgq8lBkdTW0khJhJR:-MIYqIds3xiBFpqAK65C:b-896fix) ([raw file](https://github.com/dagrofa-merkur/md_to_conf/blob/42c0217fc81641f3616390d319f7e5c6d17d5bbf/md2conf.py#L339)):*
<details><summary><i>Previously, nbali (Balázs Németh) wrote…</i></summary><blockquote>

just make this call `get_child_pages`, and you are done, you don't need the 
```
            for child_page_id in child_pages:
                get_child_pages(child_page_id)

```
part

not to mention you don't save that return value anywhere, so that call is useless
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-01 20:08 UTC, nbali approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/dagrofa-merkur/md_to_conf/3)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-01 20:10 UTC, merged